<?php

namespace AppBundle\Repository;

/**
 * EcoleProfesseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EcoleProfesseurRepository extends \Doctrine\ORM\EntityRepository
{
}
