<?php

namespace AppBundle\Repository;

/**
 * EleveClasseEcoleAnneeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EleveClasseEcoleAnneeRepository extends \Doctrine\ORM\EntityRepository
{
}
